#!/usr/bin/env python3
"""Inline engine/uptick-engine.js into main.js as a self-contained module.

Obsidian loads main.js as a single file, so the plugin cannot require() a
sibling module. The engine is therefore copied in -- but inside an IIFE, not at
top level: main.js has its own RANKS, rankFor and levelThreshold from the view
layer, and dropping the engine into the same scope collides with all three.

Run after changing the engine:

    python3 tools/inline-engine.py

Rewrites the block between the markers in main.js and touches nothing else.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "/* ===================== BEGIN uptick-engine.js ===================== */"
END = "/* ====================== END uptick-engine.js ====================== */"


def main() -> int:
    engine = (ROOT / "engine/uptick-engine.js").read_text()
    try:
        cut = engine.index("\nmodule.exports = {")
    except ValueError:
        sys.exit("inline-engine: no module.exports block found in the engine")
    exports = engine[cut:].strip()
    body = engine[:cut].replace('"use strict";\n', "", 1)
    inner = exports.replace("module.exports = {", "return {", 1)

    block = (
        BEGIN + "\n"
        "/* Generated by tools/inline-engine.py from engine/uptick-engine.js.\n"
        " * Do not edit here. Edit the engine, re-run the tool, and let\n"
        " * parity_test.js and sync_parity_test.js confirm nothing moved.\n"
        " *\n"
        " * Wrapped in an IIFE because main.js has its own RANKS, rankFor and\n"
        " * levelThreshold for the view layer, and the engine's would collide. */\n"
        "const Engine = (function () {\n"
        + body + "\n" + inner + "\n})();\n"
        + END + "\n"
    )

    target = ROOT / "main.js"
    s = target.read_text()
    if BEGIN in s and END in s:
        s = s[:s.index(BEGIN)] + block + s[s.index(END) + len(END) + 1:]
    else:
        anchor = "module.exports = class Uptick extends Plugin {"
        if anchor not in s:
            sys.exit("inline-engine: cannot find the plugin class in main.js")
        s = s.replace(anchor, block + "\n" + anchor, 1)
    target.write_text(s)
    print(f"inline-engine: inlined {len(body.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
